### ISSUE TITLE
UniEnumExtensionのパッケージをプロジェクトから削除できない

### ISSUE THREAD

**Issue by azuma560** [pCYSl5EDgo/UniEnumExtension#1]
試しにmanifest.jsonにパッケージを追加して、やはり使わなそうだから消そうとしたのですが、削除できません。
manifest.jsonから消してもUnityのWindowをアクティブにするとmanifest.jsonが書き換わってもとに戻ってしまいます。
PackageManagerから消せるか試したましたが、Removeボタンが表示されず、やはり消せません。
どうすればプロジェクトから完全に除くことができるでしょうか。

```
,
  "lock": {
    "unienumextension": {
      "hash": "a8972567b8865c247e72edae2eed243412dc367e",
      "revision": "HEAD"
    }
  }
```

**Comment by pCYSl5EDgo** [comment]
Issueありがとうございます。

BOOTHの有料版をインストールしていないと仮定して以下を記述しています。

Assetsフォルダと同階層にPackagesフォルダがあります。
そのPackagesフォルダ以下にUniEnumExtensフォルダがありませんか？
お手数ですが、UniEnumExtensionsフォルダを削除した上でmanifest.jsonから手動で削除してください。

よろしくお願いいたします。

**Comment by azuma560** [comment]
ありがとうございます。
GitHubからcloneしたものをインストールしています。

Packagesフォルダには見えてますが、Deleteを選択できず削除できません。
Unity2018.4.10を使用しています。

![image](https://user-images.githubusercontent.com/29162428/66695352-7d05f680-ecfb-11e9-8d0d-55c444c92630.png)

**Comment by pCYSl5EDgo** [comment]
インストール経路情報ありがとうございます。
なるほど、Projectタブで右クリックからはDeleteできないのですね。
その場合はまずUnityエディタを閉じます。
そしてファイルエクスプローラーから直接フォルダごと削除し、manifest.jsonを手動編集してください。
その後エディタを起動していただければアンインストール可能です。
よろしくお願いいたします。

**Comment by azuma560** [comment]
ありがとうございます。

ファイルエクスプローラー上は、Package/フォルダにmanifest.jsonしか存在しないように見えます。そのため、フォルダを直接削除することができません。
![image](https://user-images.githubusercontent.com/29162428/66702708-8f0c8700-ed45-11e9-9bab-7d15bc6a5321.png)



以下の手順も試しましたが、削除できませんでした。

 - Unityエディタを閉じる
 - manifest.jsonを手動で編集
 - Library/ を削除
 - Unityエディタを再起動

**Comment by pCYSl5EDgo** [comment]
ありがとうございます。

ふむ……
色々と考えてみました。

manifest.json手動編集についてですが、

```
    "unienumextension": "https://github.com/pCYSl5EDgo/UniEnumExtension.git",
```

と

```
,
  "lock": {
    "unienumextension": {
      "hash": "a8972567b8865c247e72edae2eed243412dc367e",
      "revision": "HEAD"
    }
  }
```

の２箇所を削除して駄目ならちょっとよくわからないですね……
UniEnumExtensionの有効/無効のメニュー項目を使って無効化するぐらいしか無さそうです。

お力になれず申し訳ないです。

**Comment by azuma560** [comment]
1箇所しか消していなかったので、
`"unienumextension": "https://github.com/pCYSl5EDgo/UniEnumExtension.git",`
の箇所と合わせて消したところ、削除できました！

対応ありがとうございます。
すいません、お手数おかけしました。
